[package]
name = "based-htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
askama = "0.12.1"
askama_rocket = "0.12.0"
rocket = "0.5.0"
